apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-agent-credentials
  namespace: monitoring
spec:
  itemPath: "vaults/Homelab/items/Base: Grafana Cloud"
