apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: base-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: base-pool
  namespace: metallb-system
